### ISSUE TITLE
This is a need login API

### ISSUE THREAD

**Issue by eightbanner** [FlandreDaisuki/Avgle.downloader#1]
Hello

I am getting these errors shown below.

https://gyazo.com/cfad0a239399680fad157c1dd850c491

**Comment by FlandreDaisuki** [comment]
Make sure you have `python3` and `requests` module, and because of Windows, you need to add python into environment variable.

Clone this repo first and `cd` into this folder
```
/Avgle.downloader/
├── main.py
├── login.txt
```
type your login information in login.txt

```
> python main.py -l login.txt 12345
```
**!!** the option is `-L` in lowercase, not `-1`
